### ISSUE TITLE
Remove unused lines

### ISSUE THREAD

**Issue by ragasubekti** [dickymr/project-javascript-todos-console#1]
https://github.com/dickymr/project-javascript-todos-console/blob/b224db9e7f9f6b222139afab09db3406345b6449/index.js#L76-L82

**Comment by dickymr** [comment]
@ragasubekti 

![oke](https://user-images.githubusercontent.com/46373553/56020330-1c3c3800-5d31-11e9-8b16-c44df353e771.jpg)

Done. Thanks
